name: 'claims_preprocessing'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.  
# Configuration required for CLI users.  Cloud users can leave as 'default'
profile: 'default'

vars:
    source_database: tuva         # configuration required (name of the database where your data is stored)
    source_schema: core      # configuration required (name of the schema where you created staging tables)
    source_name: core        # configuration required (name of your source dataset e.g. cms_claims)

    medical_claim: "{{ source(var('source_name'),'medical_claim') }}"
    eligibility: "{{ source(var('source_name'),'eligibility') }}"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  claims_preprocessing:
    +materialized: table
    +schema: claims_preprocessing
    core:
      +materialized: table
      +schema: core

seeds:
  claims_preprocessing:
    +database: tuva         
    +schema: terminology
    +tags: terminology
